runs:
  using: 'composite'
  steps:
    # Get code from repo
    - name: Checkout code
      uses: actions/checkout@v1
    # Install NodeJS
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # Run rush install and build on our code
    - name: Install dependencies
      run: |
        node common/scripts/install-run-rush.js change -v 
        node common/scripts/install-run-rush.js install
    # Run unit tests for all packages
    - name: Run tests
      run: node common/scripts/install-run-rush.js test
