runs:
  using: 'composite'
  steps:
    # Run rush install and build on our code
    - name: Install dependencies
      run: |
        node common/scripts/install-run-rush.js change -v 
        node common/scripts/install-run-rush.js install
    # Run unit tests for all packages
    - name: Run tests
      run: node common/scripts/install-run-rush.js test
