[build]
  command = "npm run build"
  publish = "out"
  function = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# this solution uses a serverless function to process images
[[redirects]]
  from = "/_next/image*"
  query = { url = ":url", w = ":width", q = ":quality" }
  to = "/.netlify/functions/image?url=:url&w=:width&q=:quality"
  status = 200

# Cloudinary account to handle image processing
# [[redirects]]
#   from = "/_next/image*"
#   query = { url = ":url", w = ":width", q = ":quality" }
#   to = "https://res.cloudinary.com/jlengstorf/image/fetch/w_:width,q_auto,f_auto/https://next-image-on.netlify.app/:url"
#   status = 200