[build]
  command = "npm run build"
  publish = "out"
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@ampproject/toolbox-optimizer", "sharp", "@prisma/client", "next"]
[[headers]]
  for = "https://development.bereghici.dev/*"
  [headers.values]
    X-Robots-Tag = "noindex"
