# Name of workflow
name: Main workflow

# When workflow is triggered
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
# Jobs to carry out
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Run rush install and build on our code
      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js change -v 
          node common/scripts/install-run-rush.js install
      # Run eslint to check all packages
      - name: Lint packages
        run: node common/scripts/install-run-rush.js lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      CI: true
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Run rush install
      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js change -v 
          node common/scripts/install-run-rush.js install
      # Run unit tests for all packages
      - name: Run tests
        run: node common/scripts/install-run-rush.js test
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        app-name: [admin, client]
        include:
          - app-name: admin
            app: '@bereghici/admin-app'
            build-dir: 'apps/admin/build'
            site-id: NETLIFY_ADMIN_SITE_ID
            dev-site-id: DEV_NETLIFY_ADMIN_SITE_ID
          - app-name: client
            app: '@bereghici/client-app'
            build-dir: 'apps/client/build'
            site-id: NETLIFY_SITE_ID
            dev-site-id: DEV_NETLIFY_SITE_ID
    needs: [lint, test]
    # Steps in job
    steps:
      # Set conditional environment variables
      - name: Set environment variables
        run: |
          if [[ "${{ startsWith(github.ref, 'refs/tags/v') }}" == "true" ]]; then
            echo "CURRENT_NETLIFY_SITE_ID=${{ secrets[matrix.site-id] }}" >> $GITHUB_ENV
          else 
            echo "CURRENT_NETLIFY_SITE_ID=${{ secrets[matrix.dev-site-id] }}" >> $GITHUB_ENV
          fi
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Run rush install and build on our code
      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js change -v
          node common/scripts/install-run-rush.js install
      - name: Get changed files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
          fileOutput: ','
      # Find changed projects to build it
      - name: Find changed projects
        id: changedProjects
        run: |
          PROJECTS="$(node tools/detect-changed-projects ${{ steps.file_changes.outputs.files}} )"
          echo $PROJECTS
          echo '${{ steps.file_changes.outputs.files}}'
          echo "::set-output name=PROJECTS::$PROJECTS"
      # Build app
      - name: Build ${{ matrix.app-name }} app
        if: ${{ contains(steps.changedProjects.outputs.projects, matrix.app) }}
        run: node common/scripts/install-run-rush.js rebuild --verbose --to ${{ matrix.app }}
      # Deploy app to netlify
      - name: Deploy ${{ matrix.app-name }} app to netlify
        if: ${{ contains(steps.changedProjects.outputs.projects, matrix.app) }}
        uses: nwtgck/actions-netlify@v1.2.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.CURRENT_NETLIFY_SITE_ID }}
        with:
          publish-dir: ${{ matrix.build-dir }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-deploy: ${{ github.event_name != 'pull_request' }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
