# Name of workflow
name: Pull requests workflow

# When workflow is triggered
on:
  pull_request:
    branches:
      - main
# Jobs to carry out
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Run rush install and build on our code
      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js change -v 
          node common/scripts/install-run-rush.js install
      # Run eslint to check all packages
      - name: Lint packages
        run: node common/scripts/install-run-rush.js lint
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Run rush install and build on our code
      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js change -v 
          node common/scripts/install-run-rush.js install
      # Run unit tests for all packages
      - name: Run tests
        run: node common/scripts/install-run-rush.js test
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    needs: [lint, test]
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Run rush install and build on our code
      - name: Install dependencies
        run: |
          node common/scripts/install-run-rush.js change -v
          node common/scripts/install-run-rush.js install
      # Build client app
      - name: Find changed projects
        id: changedProjects
        run: |
          projects="$(node tools/detect-changed-projects)"
          echo "::set-output name=projects::$projects"
      - name: Build client app
        if: contains(${{ steps.changedProjects.outputs.projects }}, '@bereghici/client-app')
        run: node common/scripts/install-run-rush.js rebuild --verbose --to @bereghici/client-app
      - name: Deploy client app to netlify
        if: contains(${{ steps.changedProjects.outputs.projects }}, '@bereghici/client-app')
        uses: nwtgck/actions-netlify@v1.2.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          publish-dir: 'apps/client/build'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          github-deployment-description: 'Client app preview'
      - name: Build admin app
        if: contains(${{ steps.changedProjects.outputs.projects }}, '@bereghici/admin-app')
        run: node common/scripts/install-run-rush.js rebuild --verbose --to @bereghici/admin-app
      - name: Deploy admin app to netlify
        if: contains(${{ steps.changedProjects.outputs.projects }}, '@bereghici/admin-app')
        uses: nwtgck/actions-netlify@v1.2.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_ADMIN_SITE_ID }}
        with:
          publish-dir: 'apps/admin/build'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          github-deployment-description: 'Admin app preview'
