# Name of workflow
name: Release workflow

# When workflow is triggered
on:
  push:
    branches:
      - main
# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    env:
      CI: true
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Run rush install and build on our code
      - name: Install dependencies
        run: node common/scripts/install-run-rush.js change -v && node common/scripts/install-run-rush.js install
      # Run eslint to check all packages
      - name: Lint packages
        run: node common/scripts/install-run-rush.js lint
      # Run unit tests for all packages
      - name: Run tests
        run: node common/scripts/install-run-rush.js test
      # Build client app
      - name: Build client app
        run: node common/scripts/install-run-rush.js rebuild --verbose --to @bereghici/client-app
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.RELEASE_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=apps/client/build --prod
